version: '3.6'
services:
  zookeeper:
    hostname: zookeeper
    image: gcr.io/google_containers/kubernetes-zookeeper:1.0-3.4.10
    ports:
      - "2181:2181"
  kafka:
    image: gcr.io/google_containers/kubernetes-kafka:1.0-10.2.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
